- alias: hasura
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: dedication76
  name: dedication76
- alias: test
  config:
    configmap: controller-conf
    namespace: hasura
  data: null
  kubeContext: doubtful36
  name: doubtful36
